### ISSUE TITLE
Ticking Entity Errors (Fabric, 1.21.1, 0.6.2)

### ISSUE THREAD

**Issue by jflec** [pufmat/attributesmod#11]
I'm a bit sleep deprived, so I can't do a deep dive right now. However, I ran into this issue after updating. I'll check if it's a mod conflict after I get some sleep, but since version 0.6.2 was released not too long ago, I figured I'd mention it:

`com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 5 but got 3. Expected types were [net.minecraft.class_1309, float, net.minecraft.class_1282, float, float], actual types were [java.lang.Float, java.lang.Float, java.lang.Float].
	at knot//com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationRuntime.checkArgumentCount(WrapOperationRuntime.java:10)
	at knot//net.minecraft.class_1309.mixinextras$bridge$method_5496$613(class_1309.java)
	at knot//net.minecraft.class_1309.wrapOperation$hmk000$puffish_attributes$wrapOperationAtApplyArmorToDamage(class_1309.java:39351)
	at knot//net.minecraft.class_1309.method_6132(class_1309.java:1701)
	at knot//net.minecraft.class_1309.method_6074(class_1309.java:1753)
	at knot//net.minecraft.class_1309.method_5643(class_1309.java:1194)
	at knot//net.minecraft.class_1420.method_5643(class_1420.java:225)
	at knot//net.minecraft.class_1297.method_5730(class_1297.java:605)
	at knot//net.minecraft.class_1297.method_5670(class_1297.java:545)
	at knot//net.minecraft.class_1309.method_5670(class_1309.java:406)
	at knot//net.minecraft.class_1308.method_5670(class_1308.java:302)
	at knot//net.minecraft.class_1297.method_5773(class_1297.java:487)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2468)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:372)
	at knot//net.minecraft.class_1420.method_5773(class_1420.java:131)
	at knot//net.minecraft.class_3218.mixinextras$bridge$method_5773$257(class_3218.java)
	at knot//net.minecraft.class_3218.wrapOperation$hjk001$porting_lib_entity$preEntityTick(class_3218.java:16307)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:770)
	at knot//net.minecraft.class_1937.mixinextras$bridge$accept$206(class_1937.java)
	at knot//com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at knot//net.minecraft.class_1937.wrapOperation$gje000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:12583)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:372)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

**Comment by pufmat** [comment]
Thanks for reporting it very fast. I have made a mistake when porting 0.6.2 update from older versions to 1.21. Version 0.6.3 fixes this issue.
