### ISSUE TITLE
Pufferfish Attributes mod and TinyInv Mod are not compatible due to "value is null"  ?

### ISSUE THREAD

**Issue by SecretSeptus** [pufmat/attributesmod#4]
I am currently working on a modpack that involves extruded character progression and Pufferfish Attributes is the only mod that allows me to give players Fortune as an Attribute, however it also does not want to load the world when installed together with TinyInv, a mod that uses Attributes to dynamicaly control (reduce) player inventory size.

**The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.puffish.attributesmod.mixin.EntityAttributeInstanceInvoker.invokeGetModifiersByOperation(net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation)" because the return value of "net.puffish.attributesmod.util.Signed.value()" is null**

Crash file
[crash-2024-05-31_16.37.41-server.txt](https://github.com/user-attachments/files/15515333/crash-2024-05-31_16.37.41-server.txt)

Cut out from the log file

**[16:37:41] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:145) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.puffish.attributesmod.mixin.EntityAttributeInstanceInvoker.invokeGetModifiersByOperation(net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation)" because the return value of "net.puffish.attributesmod.util.Signed.value()" is null
	at net.puffish.attributesmod.AttributesMod.applyAttributeModifiers(AttributesMod.java:170) ~[puffish_attributes-0.2.0-1.20-forge.jar%23444!/:?]
	at net.minecraft.world.entity.LivingEntity.localvar$ddn000$modifyVariableAtHeal(LivingEntity.java:13576) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_5634_(LivingEntity.java) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.world.entity.player.Player.sol_valheim$tick(Player.java:2833) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.world.entity.player.Player.handler$zci000$onTick(Player.java:2787) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23502!/:?]
	... 6 more**

**Comment by pufmat** [comment]
The issue is actually caused by TinyInv which injects code in a way that isn't really compatible with other mods. I have just release version 0.3.0 that has a workaround for it.
